# Generated by Django 4.2.3 on 2023-08-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='Invoice_no',
            field=models.CharField(default=127652, max_length=200),
        ),
    ]
