# Generated by Django 4.2.3 on 2023-08-03 16:00

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cartorderitem_invoice_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='Invoice_no',
            new_name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='author',
            name='vid',
        ),
        migrations.RemoveField(
            model_name='book',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='book',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='book',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='book',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cid',
        ),
        migrations.AddField(
            model_name='author',
            name='aut_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHi12345', length=10, max_length=20, prefix='AU-', unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='b_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGH12345', length=10, max_length=18, prefix='BK-', unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='sku_no',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=10, prefix='sku_', unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGH12345', length=10, max_length=30, prefix='CAT-', unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
