# Generated by Django 4.2.3 on 2023-08-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
