# Generated by Django 4.2.3 on 2023-08-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_author_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='top_rated',
            field=models.BooleanField(default=False),
        ),
    ]
