# Generated by Django 4.2.3 on 2023-08-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_author_top_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='cover_image',
            field=models.ImageField(default='a1.jpg', upload_to='user_directory_path'),
        ),
    ]
