# Generated by Django 4.2.3 on 2023-08-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_book_pre_order_alter_bookimages_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='launch_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
