# Generated by Django 4.2.3 on 2023-08-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_book_launch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='no_in_stock',
            field=models.CharField(default='100', max_length=100),
        ),
    ]
