# Generated by Django 4.2.3 on 2023-08-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_book_no_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='launched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='pre_order',
            field=models.BooleanField(default=False),
        ),
    ]
