# Generated by Django 4.2.3 on 2023-08-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_book_launched_alter_book_pre_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddField(
            model_name='book',
            name='return_policy',
            field=models.CharField(default='No Return Policy', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='warranty',
            field=models.CharField(default='No Warranty Policy', max_length=100),
        ),
    ]
