# Generated by Django 4.2.3 on 2023-08-08 00:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_book_tags_alter_author_chat_resp_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='A seasoned book writer with over 10 years of experience.', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
