# Generated by Django 4.2.3 on 2023-08-08 00:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_author_bio_alter_book_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Please write a description of your book, make it as detailed as possible', null=True),
        ),
    ]
