# Generated by Django 4.2.3 on 2023-08-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_bookreview_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='order',
            new_name='cart_order',
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐☆☆☆☆'), (2, '⭐⭐☆☆☆'), (3, '⭐⭐⭐☆☆'), (4, '⭐⭐⭐⭐☆'), (5, '⭐⭐⭐⭐⭐')], default=None),
        ),
    ]
